[[constraint]]
  name = "github.com/ChimeraCoder/anaconda"
  version = "2.0.0"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[prune]
  go-tests = true
  unused-packages = true
